#!/usr/bin/env bash

pushd() {
        builtin pushd "$@" > /dev/null
}

popd() {
        builtin popd > /dev/null
}

log_diff() {
        echo "Log files differ: ${1##*/}" >&2
}

compare_log() {
        if cmp -s "$@"; then
                printf '.'
        else
                printf 'x'
                log_diff "$@"
        fi
}

spkg_log_move() {
        sed -e 's|\[[^]]*\] \(.*\)|\1|' < ${1:?} > ${2:?}
        rm -f $1
}

compare_logs() {
        local tdir action

        tdir=${1:?}
        action=${2:?}

        spkg_log_move $logdir/spkg.log $resultdir/$tdir.$action.spkg.log
        compare_log $resultdir/$tdir.$action.spkg.log $expectdir/$tdir.$action.spkg.log

        if [[ -f $logdir/trace.log ]];then
                mv $logdir/trace.log $resultdir/$tdir.$action.trace.log
                compare_log $resultdir/$tdir.$action.trace.log $expectdir/$tdir.$action.trace.log
        fi
}

cat_pkg() {
        local pkgspec=${1:?}
        local pkgname="${pkgspec%-*-*}"
        local pkgdir="$testroot/spkg/$pkgname"
        local metadir="$pkgdir/.spkg"

        echo "Package"
        cat "$metadir/pkgspec"
        echo

        echo "Files"
        while read -r f; do
                cat "$pkgdir/$f"
        done < <(cat "$metadir/"{pkgfiles,userfiles})
        echo

        echo "Required Dirs"
        cat "$metadir/reqdirs"
        echo

        echo "Package Dirs"
        cat "$metadir/pkgdirs"
        echo

        echo "Upgrade Functions"
        cat "$metadir/upgradefns"
        echo

        echo "Replaces"
        cat "$metadir/replaces"
}
                

run_pkg() {
        local tdir tver md5

        tdir=${1:?}
        cd $tdir

        tver=${tdir%-*}

        tar caf "$srcdir/$tver.tar.gz" $tver
        md5=$(md5sum "$srcdir/$tver.tar.gz" | awk '{print $1}')
        mkdir -p $libdir/build/$tdir
        m4 -DTESTPKG_MD5SUM=$md5 SPKGBUILD.in > $libdir/build/$tdir/SPKGBUILD
        cd ..

        rm -f $logdir/spkg.log

        $spkg build $tdir &> /dev/null
        r=$?
        compare_logs "$tdir" "build"

        if (( r == 0 )); then
                $spkg install -y $tdir &> /dev/null
                r=$?
                compare_logs "$tdir" "install"
                
                if (( r == 0 )); then
                        cat_pkg "$tdir" > "$resultdir/$tdir.package.log"
                        compare_log "$resultdir/$tdir.package.log" "$expectdir/$tdir.package.log"
                fi
                
        fi
}

rem_pkg() {
        tdir=${1:?}
        rm -f $logdir/spkg.log
        $spkg uninstall -y $tdir &> /dev/null
        compare_logs "$tdir" "uninstall"
}



[[ -d testroot ]] && rm -r testroot

files=( configure Makefile.in spkg.bash spkg.conf.in SPKGBUILD.in spkg.in )

mkdir -p testroot/{results,sources,tools}


pkgver="$(awk -F"=" '/^version/{print $2}' ../configure)"

cd testroot

testroot=$PWD
spkg=$testroot/tools/bin/spkg
srcdir=$testroot/sources
libdir=$testroot/var/lib/spkg
logdir=$testroot/var/log/spkg
resultdir=$testroot/results
expectdir=${testroot%/*}/expected


src_files=$(printf '../../%s ' ${files[@]})

vdir="spkg-$pkgver"
mkdir -p $vdir
cp $src_files $vdir
cp -r ../../lib $vdir

tfile="spkg-$pkgver.tar.gz"

tar caf $tfile $vdir
cp $tfile $testroot/sources

pushd $vdir
./configure --prefix=$testroot/tools \
            --exec-prefix=$testroot/tools/bin \
            --with-sysroot=$testroot
make install
popd

cp -r ../pkgs .

cd pkgs

# Simple package with bin and etc
run_pkg testpkg-1.0.0-1

# 2 libraries (multiple links to same directory)
run_pkg testpkg-lib1-1.0.0-1

# Merges testpkg and testpg-lib1 
# And changes library names (uninstall should remove old)
run_pkg testpkg-2.0.0-1

# Change to file in usr/share/lib1
run_pkg testpkg-2.0.1-1

# Modified .conf file and changes /etc/spkg.conf in files system
# to simulate user change - should create .spkgnew file
# Also outputs info for pre/post install/uninstall functions
# Also adds files with different permissions
# Also has file containing /var/lib/spkg text - should create warning
run_pkg testpkg-2.1.0-1

# New package with file owned by spkg
# Should fail
run_pkg testpkg2-1.0.0-1

# And uninstall testpkg
rem_pkg testpkg-2.1.0-1

printf '\n'
